version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
    container_name: mindlab-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - ${LOCAL_APP_PORT}:4000
    depends_on:
      - db

volumes:
  pgdata:
